/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_Point2d */

#ifndef _Included_com_movlad_pcl_ICP
#define _Included_com_movlad_pcl_ICP
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_movlad_pcl_ICP
	* Method:    alloc
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_com_movlad_pcl_ICP_alloc
	(JNIEnv *, jobject);

	/*
	* Class:     com_movlad_pcl_ICP
	* Method:    dispose
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_com_movlad_pcl_ICP_dispose
	(JNIEnv *, jobject);

	/*
	* Class:     com_movlad_pcl_ICP
	* Method:    getX
	* Signature: ()F
	*/
	JNIEXPORT jfloatArray JNICALL Java_com_movlad_pcl_ICP_getTransformation
	(JNIEnv *, jobject);

	/*
	* Class:     com_movlad_pcl_ICP
	* Method:    setX
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_com_movlad_pcl_ICP_set
	(JNIEnv *, jobject, jfloat);

	/*
	* Class:     com_movlad_pcl_ICP
	* Method:    getY
	* Signature: ()F
	*/
	JNIEXPORT jfloat JNICALL Java_com_movlad_pcl_Point2d_getY
	(JNIEnv *, jobject);

	/*
	* Class:     com_movlad_pcl_ICP
	* Method:    setY
	* Signature: (F)V
	*/
	JNIEXPORT void JNICALL Java_com_movlad_pcl_Point2d_setY
	(JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
